### ISSUE TITLE
Simplify .cfg file by using [n.wildcard]

### ISSUE THREAD

**Issue by genotrance** [KeepCoolWithCoolidge/nimlibxlsxwriter#5]
Nimgen has the option to provide wildcard search/replace options. You could simplify the .cfg by doing the following:-

```
[n.wildcard]
wildcard = "*.nim"

search.8t = "8_t"
replace.8t = "8"

search.16t = "16_t"
replace.16t = "16"

search.32t = "32_t"
replace.32t = "32"
```

This way, any `.nim` file specified will automatically have those search/replace changes applied to them.

See the [nimbigwig](https://github.com/genotrance/nimbigwig) project for how this has been used.

**Comment by KeepCoolWithCoolidge** [comment]
Followed your advice and used wildcard.
