### ISSUE TITLE
Sparse checkout

### ISSUE THREAD

**Issue by genotrance** [KeepCoolWithCoolidge/nimlibxlsxwriter#6]
Given this is a DLL wrapper, it's not required to checkout the entire project. A sparse checkout of just the include directory should be good enough. See how [nimssl](https://github.com/genotrance/nimssl/blob/master/nimssl.cfg#L13) does a sparse checkout.

**Comment by KeepCoolWithCoolidge** [comment]
Looked at your example and used sparse checkout as suggested.
